# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
  
  

stages:
- stage: Archive
  displayName: Archive stage
  jobs:  
  - job: Archive
    displayName: Archive
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        
        
    

    - script: |
        b="$(git branch -r)"
        echo "$b"
        a="$(git diff --name-only --diff-filter=ACTRM origin/master...origin/Release)"
        echo "$a" > file.txt
        

        mkdir zipfiles

        while read p; do
            echo "$p"
            cp --parents "$p" zipfiles
        done <file.txt

        ls zipfiles -la
    
    - script: zip -r zipfiles.zip zipfiles
    
    - task: CopyFiles@2
      inputs:
          Contents: "*zip"
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'changedfiles'


              

        

    
