# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
  
  
stages:
- stage: Archive
  displayName: Archive stage
  jobs:  
  - job: Archive
    displayName: Archive_changedfiles
    pool:
      vmImage: ubuntu-latest
    steps:
    
        
    - script: |
        b="$(git branch -r)"
        echo "$b"
        a="$(git diff --name-only --diff-filter=AMCRT origin/master...origin/Release)"
        echo "$a" > file.txt
        

        mkdir changedzipfiles

        while read p; do
            echo "$p"
            cp "$p" changedzipfiles
        done <file.txt

         
    
    - script: zip -r changedzipfiles.zip changedzipfiles
    
    - task: CopyFiles@2
      inputs:
          Contents: "*zip"
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'changedfiles'
        publishLocation: 'Container'
         
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    
    


              

        

    
